### ISSUE TITLE
Error when deactivating role

### ISSUE THREAD

**Issue by fruehanp1** [gpeterso/alma-role-toggler#5]
I have this App installed in our Alma instance and when I try to use it I get an error that says, "Failed to Update User."

When looking at the Javascript Console I see this:
`t {ok: false, status: 400, statusText: "OK", message: "Mandatory field is invalid. For field user_role Re…d: AcqDeptSCSU. Valid options are: Service Units.", error: {…}}
error:
errorList: {error: Array(1)}
errorsExist: true
result: null
__proto__: Object
message: "Mandatory field is invalid. For field user_role Receiving Operator role parameter with type [serviceUnit] , received: AcqDeptSCSU. Valid options are: Service Units."
ok: false
status: 400
statusText: "OK"
__proto__: Object`

So I can see that it is an error with a particular role and once I resolved the issue with that role the error resolved.

Would it be possible to update the app to include the error message so that a user can troubleshoot? Another solution would be to allow all other roles to proceed and exclude the one with an issue.

**Comment by gpeterso** [comment]
Hi @fruehanp1, 

Thanks for the suggestion. I just pushed out a [new release](/gpeterso/alma-role-toggler/releases/tag/v0.2.0). Let me know if you run into any other issues.
