### ISSUE TITLE
change the text of the link to the Chinese 

### ISSUE THREAD

**Issue by YoelKortick** [gpeterso/alma-role-toggler#9]
Jeff:
Hi.  The 'Delete Your Sets' cloud app is very nice.
I have received this comment which seems logical and I think should be done.
In the screenshot below make the following change:
Change 
中文
To
簡體中文

This will make it more exact (thus specifying that it is simplified Chinese and not traditional Chinese).

![image](https://user-images.githubusercontent.com/13975746/122719922-7d4be880-d277-11eb-96f2-1e4eafb94356.png)

**Comment by gpeterso** [comment]
Hi @YoelKortick! 

This is the the Role Toggler repository. Did you intend to open an issue in [this repo](https://github.com/geocode64/delete-sets) instead?

Jeff

**Comment by YoelKortick** [comment]
Sorry for the confusion Jeff.  I opened this in the relevant Git Hub repository (for "delete sets").  Here in "role toggle" it can be deleted.

**Comment by YoelKortick** [comment]
Sorry for the confusion Jeff. I opened this in the relevant Git Hub repository (for "delete sets"). Here in "role toggle" it can be deleted.


***@***.***D7674D.F9AC7290]
